<!doctype html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <?=
        $this->headTitle('Aid - Project')->setSeparator(' - ')->setAutoEscape(false);

        ?>

        <!-- Bootstrap core CSS -->
        <link href="/statics/aidview/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom fonts for this template -->
        <link href="/statics/aidview/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- Plugin CSS -->
        <link href="/statics/aidview/vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">
    </head>

    <body id="page-top">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Billig.<b style="color: blue;">ru </b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Документация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/test/handlers">ТЕСТ</a>
                        </li>
                    </ul>
                    <span class="navbar-text">
                      Документация api для проекта billig.ru
                    </span>
                </div>
            </div>
        </nav>

        <div class="container">
            <h1>ТЕСТ</h1>
            <hr />
            <div class="row">
                <div class="col-6">
                <?php foreach ($items as $action=>$methods): ?>
                    <h3><?=$action?></h3>
                    <form method="post">
                    <?php foreach ($methods as $method): ?>
                        <input type="submit" name="method" class="btn btn-link" value="<?=$method ?>"><br />
                        <input type="hidden" name="action" value="<?= $action ?>">
                    <?php endforeach; ?>
                    </form>
                <?php endforeach; ?>
                </div>
                <?php if(!empty($postData)): ?>
                <div class="col-6" >
                    <pre style="background: black; color: #00e300; overflow: auto; min-height: 600px; padding: 15px;">

<?= json_encode($postData, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES); ?>
                    </pre>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </body>

</html>