<?php
namespace Test\Controller;

use Aid\Model\Orders;
use Test\DataForTesting\ClassHandlers;
use Zend\Json\Server\Exception\ErrorException;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;


class IndexController extends AbstractActionController
{

    public function onDispatch(MvcEvent $e)
    {
        session_start();
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }



    public function sendRequest(array $data, $action, $method, $hash)
    {
        $client = new \Zend\Json\Server\Client("http://{$_SERVER['HTTP_HOST']}/aid/".$hash."/run/".$action);

        try
        {
            $e = $client->call( $method, $data);
        }
        catch (ErrorException $e)
        {
            $e = $client->getLastResponse()->getError();
        }

        if(preg_match('/add(\w)?/m',$method)){
            $_SESSION[$action][$method] = $e;
        }

        return $e;
    }

//http://192.168.33.11/test/models
    public function indexAction()
    {
        return new ViewModel();
    }

    public function handlersAction()
    {
        $postData = [];
        $request = $this->getRequest();
        if($request->isPost()){

            $class = strtolower($request->getPost('action', null));
            $methods = $request->getPost('method', null);
            @$action = end(explode('\\', $class));

            $data = ClassHandlers::data($action, $methods);

            if (!empty($data)) {
                $postData = $this->sendRequest($data, $action, $methods, ClassHandlers::HASH);
            }else{
                throw new \Exception("Ошибка: для класса: ".$action." метод: ".$methods." не удалось найти данные");
            }
        }
        $r = [
            'orders' => [
                'getItem',
                'fethList',
            ],
        ];

//        $postData = $this->sendRequest(['id' => 2], 'professions', 'getItem', ClassHandlers::HASH);
//
//        echo __FILE__."<hr /><pre>";
//        print_r($postData);
//        die();

        return new ViewModel(['items' => $r, 'postData' => $postData]);
    }

}
