<?php
namespace Test\Controller;

use Aid\Model\Orders;
use Test\DataForTesting\ClassHandlers;
use Zend\Json\Server\Exception\ErrorException;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;


class IndexController extends AbstractActionController
{

    public function onDispatch(MvcEvent $e)
    {
        session_start();
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }



    public function sendRequest(array $data, $action, $method, $hash)
    {
        $url = "http://{$_SERVER['HTTP_HOST']}/aid/".$hash."/run/".$action;

        
        $client = new \Zend\Json\Server\Client($url);

        try
        {
            $e = $client->call($method, $data);
        }
        catch (ErrorException $e)
        {
            $e = $client->getLastResponse()->getError();
        }

        if(preg_match('/add(\w)?/m',$method)){
            $_SESSION[$action][$method] = $e;
        }

        return $e;
    }

//http://192.168.33.11/test/models
    public function indexAction()
    {
        return new ViewModel();
    }

    public function handlersAction()
    {
        $postData = [];
        $request = $this->getRequest();
        if($request->isPost()){

            $action = strtolower($request->getPost('action', null));
            $methods = $request->getPost('method', null);
            
            $data = ClassHandlers::data($action, $methods);

            if (!empty($data)) {
                $postData = $this->sendRequest($data, $action, $methods, ClassHandlers::HASH);
            }else{
                throw new \Exception("Ошибка: для класса: ".$action." метод: ".$methods." не удалось найти данные");
            }
        }
        $r = [
            'orders' => [
                'getItem',
                'fethList',
                'add',
                'delete',
            ],
            'users' => [
                'getItem',
                'fethList',
                'add',
                'delete',
            ],
            'professions' => [
                'getItem',
                'fethList',
                'add',
                'delete',
            ],
            'users_address' => [
                'getItem',
                'fethList',
                'add',
                'delete',
            ],
            'users_profession' => [
                'getItem',
                'fethList',
                'add',
                'delete',
            ]
        ];

//        $postData = $this->sendRequest(['id' => 2], 'professions', 'getItem', ClassHandlers::HASH);

        return new ViewModel(['items' => $r, 'postData' => $postData]);
    }

}
