<?php
/**
 * Created by PhpStorm.
 * User: b.akhmedov
 * Date: 27.06.18
 * Time: 17:57
 */

namespace Test\Controller;


use Aid\Model\Employee\EmployeesTable;
use Test\DataForTesting\Models;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;
use \Aid\Model;

class ModelsController extends AbstractActionController
{
    public function onDispatch(MvcEvent $e)
    {
        session_start();
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }
    
    private $tables;

    public function __construct(array $tables)
    {
        $this->tables = $tables;
    }

    private function send($class, $method)
    {
        $data = Models::getData($class, $method);

        call_user_func([$this->tables[$class], 'exchangeArray'], $data);
        $res = call_user_func([$this->tables[$class], $method]);

        

        
        if(preg_match('/save|save(\w)?/m',$method)){
            $_SESSION[$class]['id'] = $res;
        }

        return $res;
    }

    public function indexAction()
    {
        $postData = [];

        $request = $this->getRequest();
        if($request->isPost()){
            $class = $request->getPost('class', null);
            $method = $request->getPost('method', null);
            $postData = $this->send($class, $method);
        }

        $classes = $this->tables;

        $r = [];
        foreach ($classes as $c => $v){
            $methods = get_class_methods($c);
            @$smGetClass = strtolower(end(explode('\\', $c)));
            array_walk($methods, function($value, $key) use (&$r, $c)
            {
                if($value == '__construct') return;
                $r[$c][] = $value;
            });
        }



        return new ViewModel(['items' => $r, 'postData' => $postData]);
    }
}