<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('BilliG')->setSeparator(' - ')->setAutoEscape(false) ?>


</head>

<body>
<h1>TEMPLATE LOADET</h1>



<?= $this->content ?>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
</body>

</html>
