<script src="https://www.gstatic.com/firebasejs/4.8.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.8.1/firebase-messaging.js"></script>

<script>
//    // Initialize Firebase
//    // TODO: Replace with your project's customized code snippet
    var config = {
        apiKey: "zXyjP3lwqJSlXOZjZG2lZHg8ad62",
        authDomain: "aidvps.firebaseapp.com",
        databaseURL: "https://aidvps.firebaseio.com",
        projectId: "aidvps",
        storageBucket: "aidvps.appspot.com",
        messagingSenderId: "6113640198811212014"
    };
    firebase.initializeApp(config);

    const messaging = firebase.messaging();

    messaging.onMessage(function (payload) {
        console.log('Message received. ', payload);
        // ...
    });

//
//    firebase.auth().signInAnonymously().catch(function(error) {
//        // Handle Errors here.
//        var errorCode = error.code;
//        var errorMessage = error.message;
//        // ...
//
//        console.log(errorMessage);
//    });
//
////    const messaging = firebase.messaging();
////    messaging.requestPermission().then(function() {
////        console.log('Notification permission granted.');
////        // TODO(developer): Retrieve an Instance ID token for use with FCM.
////        // ...
////    }).catch(function(err) {
////        console.log('Unable to get permission to notify.', err);
////    });
//
//
//    console.log("good");



</script>

